version: '3.0'

services:
  crm-db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - nw
  web:
    build:
      context: ./backend
    image: micropyramid/django-crm:1
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - "8001:8000"
    depends_on:
      - crm-db
    command: gunicorn crm.wsgi --bind 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    networks:
      - nw
#
#  frontend:
#    build:
#      context: ./frontend
#    volumes:
#      - ./frontend:/frontend
#      - react_build:/frontend/build
#    env_file:
#      - ./frontend/.env
#    depends_on:
#      - web
#    ports:
#      - 3000:3000
#    networks:
#      - nw
#    command: npm run server
#  nginx:
#    image: nginx:latest
#    ports:
#      - 80:8080
#    volumes:
#      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
#      - react_build:/var/www/react
#    user:
#      root

networks:
  nw: {}

volumes:
  react_build:
  pg_data:
